name: 
run-name: ${{ github.actor }} creating S3 bucket
on:
  push:
    branches:
      - main
jobs:
  create_bucket:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
      
    - name: Create S3 Bucket using AWS CLI on EC2
      run:
        echo "${{ secrets.AWS_SECRET_ACCESS_KEY }}" > temporary_key.pem
        chmod 600 temporary_key.pem
        ssh -i temporary_key.pem -o StrictHostKeyChecking=no ubuntu@54.201.114.163
        aws s3api create-bucket --bucket Final-project-S3-bucket --region us-west-2a