name: Create S3 Bucket
run-name: ${{ github.actor }} creating S3 bucket
on:
  push:
    branches:
      - main
      - bucket
jobs:
  create_bucket:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        echo -n "${AWS_SECRET_ACCESS_KEY}" > temporary_key.pem
        chmod 600 temporary_key.pem
        scp -o StrictHostKeyChecking=no -i temporary_key.pem temporary_key.pem ubuntu@54.201.114.163:

    - name: Create S3 Bucket using AWS CLI on EC2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        ssh -i temporary_key.pem -o StrictHostKeyChecking=no uubuntu@54.201.114.163 << EOF
          aws s3api create-bucket --bucket Final-project-S3-bucket --region us-west-2
        EOF
